In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1,2,3], [4,5,6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [9]:
X = np.array([[0,1,2], [3,4,5]])

In [10]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [12]:
A = np.array([[1,2], [3,4]])

In [13]:
A * 10

array([[10, 20],
       [30, 40]])

In [15]:
b = np.array([10,20])

In [16]:
A * b

array([[10, 40],
       [30, 80]])

In [17]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
np.dot(a,b)

32

In [19]:
# 행렬의 곱
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [20]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [2]:
W1 = np.random.randn(2, 4)    # 가중치
b1 = np.random.randn(4)       # 편항
x = np.random.randn(10, 2)    # 입력
h = np.matmul(x, W1) + b1

In [3]:
h

array([[-1.62078818,  0.89547503,  1.36354937, -1.05626132],
       [-3.92869167,  5.26777644,  3.17353743,  1.53640149],
       [-0.91353639,  0.38303996,  1.7201478 , -0.40733631],
       [-1.27606273,  0.78989089,  1.69615115, -0.48844218],
       [ 1.66174645, -3.46909843,  0.83117979, -1.50932213],
       [-0.42914126, -0.68384588,  1.17594   , -1.21177708],
       [-2.36893396,  1.7775531 ,  1.36078815, -1.14957076],
       [-2.08294904,  2.17992552,  2.17631276,  0.1762136 ],
       [-4.18326592,  5.52610771,  3.12654533,  1.43170371],
       [-1.63767386,  1.60557426,  2.12359242,  0.14563676]])

In [4]:
def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

In [5]:
a = sigmoid(h)

In [6]:
a

array([[0.1650962 , 0.71001873, 0.79633596, 0.25802457],
       [0.01928997, 0.99487138, 0.95982621, 0.822941  ],
       [0.28627673, 0.5946061 , 0.84814787, 0.399551  ],
       [0.21822118, 0.6878079 , 0.84503138, 0.38026062],
       [0.8404723 , 0.03020438, 0.69660433, 0.18103928],
       [0.39433141, 0.33540348, 0.76421702, 0.22938677],
       [0.08557252, 0.85539446, 0.79588776, 0.2405675 ],
       [0.11076516, 0.89843228, 0.89810213, 0.54393976],
       [0.0150196 , 0.99603433, 0.95797453, 0.80716664],
       [0.16278183, 0.83279602, 0.89317518, 0.53634497]])

In [8]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

In [9]:
h

array([[ 1.52128376,  0.79740151,  1.23027474,  1.03244931],
       [ 1.39328695, -1.16786151, -1.42476212,  1.47839465],
       [ 1.79433663, -1.00738281, -1.37686987,  1.48528356],
       [ 2.52120238, -0.9603292 , -1.62630487,  1.55485088],
       [ 2.13797358, -0.46545931, -0.77808103,  1.39649802],
       [ 2.2442284 , -0.2332827 , -0.50382444,  1.35391745],
       [ 3.26148886, -1.54822057, -2.75722662,  1.77456858],
       [ 1.2937582 , -0.39831921, -0.32040886,  1.28718402],
       [ 0.79959954, -1.25969085, -1.29467168,  1.43407573],
       [ 2.47761922, -0.55266023, -1.04522179,  1.45456968]])

In [10]:
a

array([[0.82072744, 0.68941837, 0.77386666, 0.73739047],
       [0.80111647, 0.23724174, 0.19391612, 0.81432998],
       [0.85745814, 0.26749235, 0.20151218, 0.8153693 ],
       [0.92561488, 0.27681229, 0.16433719, 0.82561325],
       [0.89453959, 0.38569153, 0.31473362, 0.80162759],
       [0.90415152, 0.44194238, 0.37664233, 0.79476935],
       [0.96308376, 0.17534342, 0.05967981, 0.8550249 ],
       [0.78478262, 0.40171623, 0.42057611, 0.78367017],
       [0.68988881, 0.22102712, 0.21506313, 0.80753557],
       [0.92255787, 0.36524744, 0.2601437 , 0.81070072]])

In [11]:
s

array([[-2.84907646, -0.90043495,  1.77390078],
       [-3.16595006, -0.53517806,  1.3024339 ],
       [-3.21818289, -0.51324399,  1.34959064],
       [-3.31455393, -0.44846625,  1.37653516],
       [-3.19198164, -0.55530456,  1.48146505],
       [-3.16836388, -0.58616317,  1.54133464],
       [-3.43389528, -0.38934128,  1.27452934],
       [-3.01826264, -0.69082326,  1.467128  ],
       [-3.04419596, -0.58809695,  1.25369974],
       [-3.25445529, -0.49846018,  1.46764104]])

In [2]:
D, N = 8, 7
x = np.random.randn(1, D)      # 입력
y = np.repeat(x, N, axis = 0)  # 순전파
dy = np.random.randn(N, D)     # 무작위 기울기
dx = np.sum(dy, axis = 0, keepdims = True)  # 역전파

In [3]:
x

array([[ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474]])

In [4]:
y

array([[ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474],
       [ 0.77509954,  0.12589125, -1.20101993, -0.27471299,  0.49170894,
         0.63500107,  0.25261168,  0.67796474]])