In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1,2,3], [4,5,6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [9]:
X = np.array([[0,1,2], [3,4,5]])

In [10]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [12]:
A = np.array([[1,2], [3,4]])

In [13]:
A * 10

array([[10, 20],
       [30, 40]])

In [15]:
b = np.array([10,20])

In [16]:
A * b

array([[10, 40],
       [30, 80]])

In [17]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])

In [18]:
np.dot(a,b)

32

In [19]:
# 행렬의 곱
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [20]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])